### ISSUE TITLE
Can provide some dataset to test the demo (like default Candi Banyunibo data set)?

### ISSUE THREAD

**Issue by oscarbg** [m-schuetz/compute_rasterizer#7]
Hi,
just found this paper & project via graphics weekly news..
just compiled the demo, and seems uses that dataset by default (banyunibo_inside_morton)..
anyway to obtain that dataset?
if not can you provide some download link to some huge & equivalent data set used by the demo like retz,eclepens,etc..
are this datasets under non "open" licenses?
just wanted to test performance on my Titan V compared to a 3090..
thanks..

**Comment by oscarbg** [comment]
seems I go to fast I read now:  "add the option to drag&drop your own point clouds after vacation. We will also add a test data set by then."
anyway keep open so I get notified when dataset is added..

**Comment by josephrocca** [comment]
I'm not sure how long this will be around for, but: http://5.9.65.151/mschuetz/temporary/MorroBay.zip

From this tweet: https://twitter.com/m_schuetz/status/1526923601433268225

**Comment by m-schuetz** [comment]
> I'm not sure how long this will be around for, but: http://5.9.65.151/mschuetz/temporary/MorroBay.zip

I'll be up for a while, the temporary folder is just the place I start removing stuff when I run out of storage.

**Comment by oscarbg** [comment]
@m-schuetz 
maybe open different issue but testing of precompiled binary (https://github.com/m-schuetz/compute_rasterizer/releases/tag/build) on morro_bay_morton_102M.las from http://5.9.65.151/mschuetz/temporary/MorroBay.zip on a GTX970 (4GB memory) latest drivers 516.01 doesn't render ok..
this dataset has 100M so 4GB VRAM should be enough:1,6GB+2GB..

for example copied from demo:
```
#nodes processed	9'971
#nodes rendered	9'971
#points processed	102'103'040
#points rendered	0
#points visible	0
```

console shows errors (lots of OPENGL DEBUG CALLBACK: GL_INVALID_VALUE error generated. <offset> + <size> is greater than the value of BUFFER_SIZE for the buffer bound to <target>.):
```
<create windows>
<set input callbacks>
<glewInit done> (0.51)
compiling component ./modules/compute_loop_las/render.cs
compiling component ./modules/compute_loop_las/resolve.cs
compiling component ./modules/compute_loop_las2/render.cs
compiling component ./modules/compute_loop_las2/resolve.cs
compiling component ./modules/compute_loop_las_hqs/depth.cs
compiling component ./modules/compute_loop_las_hqs/color.cs
compiling component ./modules/compute_loop_las_hqs/resolve.cs
compiling component ./shaders/boundingBox.vs
compiling component ./shaders/boundingBox.fs
compiling component ./shaders/box.vs
compiling component ./shaders/box.fs
key: 342, scancode: 56, action: 1, mods: 4
342
key: 342, scancode: 56, action: 0, mods: 0
342
start button: 0, action: 1, mods: 0
end button: 0, action: 1, mods: 0
start button: 0, action: 0, mods: 0
start button: 0, action: 1, mods: 0
start button: 0, action: 0, mods: 0
start button: 0, action: 1, mods: 0
start button: 0, action: 0, mods: 0
start button: 0, action: 1, mods: 0
start button: 0, action: 0, mods: 0
start button: 0, action: 1, mods: 0
start button: 0, action: 0, mods: 0
key: 342, scancode: 56, action: 1, mods: 4
342
key: 342, scancode: 56, action: 0, mods: 0
342
commiting, offset: 405'471'232, size: 2'949'120
uploading, offset: 405'504'000, size: 2'905'868
numBatchesLoaded: 71
OPENGL DEBUG CALLBACK: GL_INVALID_VALUE error generated. <offset> + <size> is greater than the value of BUFFER_SIZE for the buffer bound to <target>.
OPENGL DEBUG CALLBACK: GL_INVALID_VALUE error generated. <offset> + <size> is greater than the value of BUFFER_SIZE for the buffer bound to <target>.
OPENGL DEBUG CALLBACK: GL_INVALID_VALUE error generated. <offset> + <size> is greater than the value of BUFFER_SIZE for the buffer bound to <target>.
OPENGL DEBUG CALLBACK: GL_INVALID_VALUE error generated. <offset> + <size> is greater than the value of BUFFER_SIZE for the buffer bound to <target>.
OPENGL DEBUG CALLBACK: GL_INVALID_VALUE error generated. <offset> + <size> is greater than the value of BUFFER_SIZE for the buffer bound to <target>.
OPENGL DEBUG CALLBACK: GL_INVALID_VALUE error generated. <offset> + <size> is greater than the value of BUFFER_SIZE for the buffer bound to <target>.
OPENGL DEBUG CALLBACK: GL_INVALID_VALUE error generated. <offset> + <size> is greater than the value of BUFFER_SIZE for the buffer bound to <target>.
OPENGL DEBUG CALLBACK: GL_INVALID_VALUE error generated. <offset> + <size> is greater than the value of BUFFER_SIZE for the buffer bound to <target>.
OPENGL DEBUG CALLBACK: GL_INVALID_VALUE error generated. <offset> + <size> is greater than the value of BUFFER_SIZE for the buffer bound to <target>.
OPENGL DEBUG CALLBACK: GL_INVALID_VALUE error generated. <offset> + <size> is greater than the value of BUFFER_SIZE for the buffer bound to <target>.
OPENGL DEBUG CALLBACK: GL_INVALID_VALUE error generated. <offset> + <size> is greater than the value of BUFFER_SIZE for the buffer bound to <target>.
OPENGL DEBUG CALLBACK: GL_INVALID_VALUE error generated. <offset> + <size> is greater than the value of BUFFER_SIZE for the buffer bound to <target>.
OPENGL DEBUG CALLBACK: GL_INVALID_VALUE error generated. <offset> + <size> is greater than the value of BUFFER_SIZE for the buffer bound to <target>.
OPENGL DEBUG CALLBACK: GL_INVALID_VALUE error generated. <offset> + <size> is greater than the value of BUFFER_SIZE for the buffer bound to <target>.
OPENGL DEBUG CALLBACK: GL_INVALID_VALUE error generated. <offset> + <size> is greater than the value of BUFFER_SIZE for the buffer bound to <target>.
OPENGL DEBUG CALLBACK: GL_INVALID_VALUE error generated. <offset> + <size> is greater than the value of BUFFER_SIZE for the buffer bound to <target>.
OPENGL DEBUG CALLBACK: GL_INVALID_VALUE error generated. <offset> + <size> is greater than the value of BUFFER_SIZE for the buffer bound to <target>.
OPENGL DEBUG CALLBACK: GL_INVALID_VALUE error generated. <offset> + <size> is greater than the value of BUFFER_SIZE for the buffer bound to <target>.
OPENGL DEBUG CALLBACK: GL_INVALID_VALUE error generated. <offset> + <size> is greater than the value of BUFFER_SIZE for the buffer bound to <target>.
OPENGL DEBUG CALLBACK: GL_INVALID_VALUE error generated. <offset> + <size> is greater than the value of BUFFER_SIZE for the buffer bound to <target>.
commiting, offset: 401'408'000, size: 4'128'768
uploading, offset: 401'408'000, size: 4'096'000
numBatchesLoaded: 171
OPENGL DEBUG CALLBACK: GL_INVALID_VALUE error generated. <offset> + <size> is greater than the value of BUFFER_SIZE for the buffer bound to <target>.
OPENGL DEBUG CALLBACK: GL_INVALID_VALUE error generated. <offset> + <size> is greater than the value of BUFFER_SIZE for the buffer bound to <target>.
OPENGL DEBUG CALLBACK: GL_INVALID_VALUE error generated. <offset> + <size> is greater than the value of BUFFER_SIZE for the buffer bound to <target>.
OPENGL DEBUG CALLBACK: GL_INVALID_VALUE error generated. <offset> + <size> is greater than the value of BUFFER_SIZE for the buffer bound to <target>.
OPENGL DEBUG CALLBACK: GL_INVALID_VALUE error generated. <offset> + <size> is greater than the value of BUFFER_SIZE for the buffer bound to <target>.
OPENGL DEBUG CALLBACK: GL_INVALID_VALUE error generated. <offset> + <size> is greater than the value of BUFFER_SIZE for the buffer bound to <target>.
OPENGL DEBUG CALLBACK: GL_INVALID_VALUE error generated. <offset> + <size> is greater than the value of BUFFER_SIZE for the buffer bound to <target>.
OPENGL DEBUG CALLBACK: GL_INVALID_VALUE error generated. <offset> + <size> is greater than the value of BUFFER_SIZE for the buffer bound to <target>.
OPENGL DEBUG CALLBACK: GL_INVALID_VALUE error generated. <offset> + <size> is greater than the value of BUFFER_SIZE for the buffer bound to <target>.
OPENGL DEBUG CALLBACK: GL_INVALID_VALUE error generated. <offset> + <size> is greater than the value of BUFFER_SIZE for the buffer bound to <target>.
OPENGL DEBUG CALLBACK: GL_INVALID_VALUE error generated. <offset> + <size> is greater than the value of BUFFER_SIZE for the buffer bound to <target>.
OPENGL DEBUG CALLBACK: GL_INVALID_VALUE error generated. <offset> + <size> is greater than the value of BUFFER_SIZE for the buffer bound to <target>.
OPENGL DEBUG CALLBACK: GL_INVALID_VALUE error generated. <offset> + <size> is greater than the value of BUFFER_SIZE for the buffer bound to <target>.
OPENGL DEBUG CALLBACK: GL_INVALID_VALUE error generated. <offset> + <size> is greater than the value of BUFFER_SIZE for the buffer bound to <target>.
OPENGL DEBUG CALLBACK: GL_INVALID_VALUE error generated. <offset> + <size> is greater than the value of BUFFER_SIZE for the buffer bound to <target>.
OPENGL DEBUG CALLBACK: GL_INVALID_VALUE error generated. <offset> + <size> is greater than the value of BUFFER_SIZE for the buffer bound to <target>.
OPENGL DEBUG CALLBACK: GL_INVALID_VALUE error generated. <offset> + <size> is greater than the value of BUFFER_SIZE for the buffer bound to <target>.
OPENGL DEBUG CALLBACK: GL_INVALID_VALUE error generated. <offset> + <size> is greater than the value of BUFFER_SIZE for the buffer bound to <target>.
OPENGL DEBUG CALLBACK: GL_INVALID_VALUE error generated. <offset> + <size> is greater than the value of BUFFER_SIZE for the buffer bound to <target>.
OPENGL DEBUG CALLBACK: GL_INVALID_VALUE error generated. <offset> + <size> is greater than the value of BUFFER_SIZE for the buffer bound to <target>.
OPENGL DEBUG CALLBACK: GL_INVALID_VALUE error generated. <offset> + <size> is greater than the value of BUFFER_SIZE for the buffer bound to <target>.
OPENGL DEBUG CALLBACK: GL_INVALID_VALUE error generated. <offset> + <size> is greater than the value of BUFFER_SIZE for the buffer bound to <target>.
OPENGL DEBUG CALLBACK: GL_INVALID_VALUE error generated. <offset> + <size> is greater than the value of BUFFER_SIZE for the buffer bound to <target>.
OPENGL DEBUG CALLBACK: GL_INVALID_VALUE error generated. <offset> + <size> is greater than the value of BUFFER_SIZE for the buffer bound to <target>.
OPENGL DEBUG CALLBACK: GL_INVALID_VALUE error generated. <offset> + <size> is greater than the value of BUFFER_SIZE for the buffer bound to <target>.
OPENGL DEBUG CALLBACK: GL_INVALID_VALUE error generated. <offset> + <size> is greater than the value of BUFFER_SIZE for the buffer bound to <target>.
OPENGL DEBUG CALLBACK: GL_INVALID_VALUE error generated. <offset> + <size> is greater than the value of BUFFER_SIZE for the buffer bound to <target>.
OPENGL DEBUG CALLBACK: GL_INVALID_VALUE error generated. <offset> + <size> is greater than the value of BUFFER_SIZE for the buffer bound to <target>.
commiting, offset: 397'279'232, size: 4'128'768
uploading, offset: 397'312'000, size: 4'096'000
numBatchesLoaded: 271
OPENGL DEBUG CALLBACK: GL_INVALID_VALUE error generated. <offset> + <size> is greater than the value of BUFFER_SIZE for the buffer bound to <target>.
OPENGL DEBUG CALLBACK: GL_INVALID_VALUE error generated. <offset> + <size> is greater than the value of BUFFER_SIZE for the buffer bound to <target>.
OPENGL DEBUG CALLBACK: GL_INVALID_VALUE error generated. <offset> + <size> is greater than the value of BUFFER_SIZE for the buffer bound to <target>.
OPENGL DEBUG CALLBACK: GL_INVALID_VALUE error generated. <offset> + <size> is greater than the value of BUFFER_SIZE for the buffer bound to <target>.
OPENGL DEBUG CALLBACK: GL_INVALID_VALUE error generated. <offset> + <size> is greater than the value of BUFFER_SIZE for the buffer bound to <target>.
OPENGL DEBUG CALLBACK: GL_INVALID_VALUE error generated. <offset> + <size> is greater than the value of BUFFER_SIZE for the buffer bound to <target>.
OPENGL DEBUG CALLBACK: GL_INVALID_VALUE error generated. <offset> + <size> is greater than the value of BUFFER_SIZE for the buffer bound to <target>.
OPENGL DEBUG CALLBACK: GL_INVALID_VALUE error generated. <offset> + <size> is greater than the value of BUFFER_SIZE for the buffer bound to <target>.
OPENGL DEBUG CALLBACK: GL_INVALID_VALUE error generated. <offset> + <size> is greater than the value of BUFFER_SIZE for the buffer bound to <target>.
OPENGL DEBUG CALLBACK: GL_INVALID_VALUE error generated. <offset> + <size> is greater than the value of BUFFER_SIZE for the buffer bound to <target>.
OPENGL DEBUG CALLBACK: GL_INVALID_VALUE error generated. <offset> + <size> is greater than the value of BUFFER_SIZE for the buffer bound to <target>.
OPENGL DEBUG CALLBACK: GL_INVALID_VALUE error generated. <offset> + <size> is greater than the value of BUFFER_SIZE for the buffer bound to <target>.
OPENGL DEBUG CALLBACK: GL_INVALID_VALUE error generated. <offset> + <size> is greater than the value of BUFFER_SIZE for the buffer bound to <target>.
OPENGL DEBUG CALLBACK: GL_INVALID_VALUE error generated. <offset> + <size> is greater than the value of BUFFER_SIZE for the buffer bound to <target>.
OPENGL DEBUG CALLBACK: GL_INVALID_VALUE error generated. <offset> + <size> is greater than the value of BUFFER_SIZE for the buffer bound to <target>.
OPENGL DEBUG CALLBACK: GL_INVALID_VALUE error generated. <offset> + <size> is greater than the value of BUFFER_SIZE for the buffer bound to <target>.
OPENGL DEBUG CALLBACK: GL_INVALID_VALUE error generated. <offset> + <size> is greater than the value of BUFFER_SIZE for the buffer bound to <target>.
OPENGL DEBUG CALLBACK: GL_INVALID_VALUE error generated. <offset> + <size> is greater than the value of BUFFER_SIZE for the buffer bound to <target>.
OPENGL DEBUG CALLBACK: GL_INVALID_VALUE error generated. <offset> + <size> is greater than the value of BUFFER_SIZE for the buffer bound to <target>.
OPENGL DEBUG CALLBACK: GL_INVALID_VALUE error generated. <offset> + <size> is greater than the value of BUFFER_SIZE for the buffer bound to <target>.
OPENGL DEBUG CALLBACK: GL_INVALID_VALUE error generated. <offset> + <size> is greater than the value of BUFFER_SIZE for the buffer bound to <target>.
OPENGL DEBUG CALLBACK: GL_INVALID_VALUE error generated. <offset> + <size> is greater than the value of BUFFER_SIZE for the buffer bound to <target>.
OPENGL DEBUG CALLBACK: GL_INVALID_VALUE error generated. <offset> + <size> is greater than the value of BUFFER_SIZE for the buffer bound to <target>.
OPENGL DEBUG CALLBACK: GL_INVALID_VALUE error generated. <offset> + <size> is greater than the value of BUFFER_SIZE for the buffer bound to <target>.
OPENGL DEBUG CALLBACK: GL_INVALID_VALUE error generated. <offset> + <size> is greater than the value of BUFFER_SIZE for the buffer bound to <target>.
OPENGL DEBUG CALLBACK: GL_INVALID_VALUE error generated. <offset> + <size> is greater than the value of BUFFER_SIZE for the buffer bound to <target>.
OPENGL DEBUG CALLBACK: GL_INVALID_VALUE error generated. <offset> + <size> is greater than the value of BUFFER_SIZE for the buffer bound to <target>.
commiting, offset: 393'216'000, size: 4'128'768
uploading, offset: 393'216'000, size: 4'096'000
numBatchesLoaded: 371
```

**Comment by m-schuetz** [comment]
Might be an issue with [GL_ARB_sparse_buffer](https://www.khronos.org/registry/OpenGL/extensions/ARB/ARB_sparse_buffer.txt) and/or that GPUs older than the Pascal series are not supported. I'm using a sparse buffer that allocates 16GB virtual memory at startup, but only physically allocates as much memory as needed to load the point cloud. Since it's 16GB virtual and not actual physical memory, I was under the assumption that it should be working on GPUs with 4GB. I'll give it a try on my GTX1060 3GB when I get to it. If it works there, then the issue might be that something is not working on GPUs older than that.

**Comment by m-schuetz** [comment]
Btw, this earlier branch/tag doesn't use sparse buffers so maybe it could work there: https://github.com/m-schuetz/compute_rasterizer/tree/compute_rasterizer_2022

But it also doesn't support drag&drop so you'll have to modify main.cpp to load your own data set, and it also only supports loading a single point cloud. The reason for using sparse buffers is that it makes it easy to put several different point cloud data sets into one huge large buffer, which makes implementing stuff a whole lot easier.

**Comment by m-schuetz** [comment]
> maybe open different issue but testing of precompiled binary (https://github.com/m-schuetz/compute_rasterizer/releases/tag/build) on morro_bay_morton_102M.las from http://5.9.65.151/mschuetz/temporary/MorroBay.zip on a GTX970 (4GB memory) latest drivers 516.01 doesn't render ok..
this dataset has 100M so 4GB VRAM should be enough:1,6GB+2GB..

Loading 100M points works on my 1060 3GB (it's already close to the limit, though). I can only assume that there might be issues with GPU generations before Pascal.

**Comment by oscarbg** [comment]
Hi @m-schuetz thanks for all info and sorry for delay in answering..
curiously got it working on 970 by resizing window **horizontally** before dropping/loading the dataset..
I'm on a 4k monitor so window opened was perhaps around 3600x2000..
resizing vertically doesn't fix the problem but resizing horizontally to half screen approx. it works.. so seems the issue is perhaps width>2048 as also upon correct loading scene with a window say 1800x2000 if I resize to expand horizontally width>2048 also starts failing with same log..
can you test on a 4k desktop, and test if it continues working on Pascal on a 4K window? I suspect not, as I tested demo days ago on a Titan V on 4k desktop and also failed similarly..
searching 2048 max GL values I get:
```
GL_MAX_SPARSE_3D_TEXTURE_SIZE_ARB  2,048
GL_MAX_SPARSE_ARRAY_TEXTURE_LAYERS_ARB 2048
GL_MAX_3D_TEXTURE_SIZE 2,048
```

**Comment by m-schuetz** [comment]
> so seems the issue is perhaps width>2048 as also upon correct loading scene with a window say 1800x2000 if I resize to expand horizontally width>2048 also starts failing with same log..

Ah, then the or one of the problems is the hardcoded maximum size (2048*2048) of the framebuffer (actually a regular storage buffer where points are rasterized into with atomicMin): https://github.com/m-schuetz/compute_rasterizer/blob/master/modules/compute_loop_las/compute_loop_las.h#L96

Thanks for the hint, I'll have to fix that.

**Comment by m-schuetz** [comment]
Fixed - now supports larger window sizes.

**Comment by oscarbg** [comment]
thanks! will try soon..
